version: "3.9"

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./etc/php-fpm/Dockerfile
    container_name: php-fpm
    environment:
      MYSQL_DATABASE: "hello"
      MYSQL_PASSWORD: "OLr/rb3+A3HQMpnyI1c/WAlf+rc="
      MYSQL_SERVER: "mysql"
      MYSQL_USER: "hello"
    networks:
      - backend
      - frontend
    volumes:
      - ./app:/app

  nginx:
    build:
      context: .
      dockerfile: ./etc/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - php-fpm
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./etc/nginx/development/ssl:/etc/ssl
      - ./etc/nginx/development/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    build:
      context: .
      dockerfile: ./etc/mysql/Dockerfile
    container_name: mysql
    environment:
      MYSQL_DATABASE: "hello"
      MYSQL_PASSWORD: "OLr/rb3+A3HQMpnyI1c/WAlf+rc="
      MYSQL_ROOT_PASSWORD: "BCML9z2cL5e/gu6pzCbGrxuCa00="
      MYSQL_USER: "hello"
    networks:
      - backend
    platform: linux/amd64
    volumes:
      - mysql:/var/lib/mysql

networks:
  backend:
  frontend:

volumes:
  mysql: