version: "3.9"

services:
  nginx:
    image: ironex/nginx
    networks:
      - frontend
    ports:
      - 80:80
    volumes:
    - ./app/var:/app/var

  php-fpm:
    image: ironex/php-fpm
    networks:
      - backend
      - frontend
    volumes:
    - ./app/var:/app/var
    - ./app/vendor:/app/vendor

  composer:
    image: ironex/composer
    volumes:
    - ./app/vendor:/app/vendor

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "StyKmBdAMAdhfppzr6"
    image: ironex/mysql
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - hello_mysql:/var/lib/mysql

  adminer:
    image: ironex/adminer
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080

networks:
  backend:
  frontend:

volumes:
  hello_mysql: