version: "3.9"

services:
  nginx:
    image: ironex/nginx
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    platform: linux/amd64
    volumes:
      - var:/app/var
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  php-fpm:
    image: ironex/php-fpm
    networks:
      - backend
      - frontend
    platform: linux/amd64
    volumes:
      - var:/app/var
    depends_on:
      - nginx

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "StyKmBdAMAdhfppzr6"
    image: ironex/mysql
    networks:
      - backend
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  composer:
    image: ironex/composer
    networks:
      - backend
    platform: linux/amd64
    volumes:
      - ./app:/app
    depends_on:
      - php-fpm

  certbot:
    image: ironex/composer
    networks:
      - frontend
    platform: linux/amd64
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx

networks:
  backend:
  frontend:

volumes:
  certbot-etc:
  certbot-var:
  mysql:
  var:
  vendor: