version: "3.9"

services:
  php-fpm:
    environment:
      MYSQL_DATABASE: /run/secrets/mysql_database
      MYSQL_PASSWORD: /run/secrets/mysql_password
      MYSQL_SERVER: "mysql"
      MYSQL_USER: /run/secrets/mysql_user
    image: ironex/php-fpm
    networks:
      - backend
      - frontend
    volumes:
      - var:/app/var
      - vendor:/app/vendor

  nginx:
    depends_on:
      - php-fpm
    image: ironex/nginx
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - var:/app/var
      - certbot:/etc/letsencrypt

  mysql:
    environment:
      MYSQL_DATABASE: /run/secrets/mysql_database
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER: /run/secrets/mysql_user
    image: ironex/mysql
    networks:
      - backend
    volumes:
      - mysql:/var/lib/mysql

networks:
  backend:
  frontend:

# Volumes are prefixed with stack name (stack_volume) when using docker stack deploy <stack> command
volumes:
  certbot:
  mysql:
  var:
  vendor: