version: "3.9"

services:
  nginx:
    image: ironex/nginx
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    platform: linux/amd64
    volumes:
    - var:/app/var

  php-fpm:
    image: ironex/php-fpm
    networks:
      - backend
      - frontend
    platform: linux/amd64
    volumes:
    - var:/app/var
    - vendor:/app/vendor

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "StyKmBdAMAdhfppzr6"
      image: ironex/mysql
    networks:
      - backend
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

networks:
  backend:
  frontend:

volumes:
  var:
  vendor: