version: "3.9"

services:
  nginx:
    image: ironex/nginx
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    volumes:
      - var:/app/var
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  php-fpm:
    depends_on:
      - nginx
    image: ironex/php-fpm
    networks:
      - backend
      - frontend
    restart: on-failure
    volumes:
      - var:/app/var

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "StyKmBdAMAdhfppzr6"
    image: ironex/mysql
    networks:
      - backend
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql

  composer:
    depends_on:
      - php-fpm
    image: ironex/composer
    networks:
      - backend
    restart: on-failure
    volumes:
      - ./app:/app

  certbot:
    depends_on:
      - nginx
    image: ironex/certbot
    networks:
      - frontend
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

networks:
  backend:
  frontend:

volumes:
  certbot-etc:
  certbot-var:
  mysql:
  var:
  vendor: