version: "3.9"

services:
  php-fpm:
    image: ironex/php-fpm
    networks:
      - backend
      - frontend
    volumes:
      - var:/app/var

  nginx:
    depends_on:
      - php-fpm
    image: ironex/nginx
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - var:/app/var
      - certbot:/etc/letsencrypt

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "StyKmBdAMAdhfppzr6"
    image: ironex/mysql
    networks:
      - backend
    volumes:
      - mysql:/var/lib/mysql

networks:
  backend:
  frontend:

volumes:
  certbot:
  mysql:
  var:
  vendor: