version: "3.9"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./etc/nginx/Dockerfile
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    platform: linux/amd64
    volumes:
      - ./app:/app
      - ./etc/nginx/development/ssl:/etc/ssl
      - ./etc/nginx/development/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./etc/php-fpm/Dockerfile
    networks:
      - backend
      - frontend
    platform: linux/amd64
    volumes:
      - ./app:/app
    depends_on:
      - nginx

  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "StyKmBdAMAdhfppzr6"
    build:
      context: .
      dockerfile: ./etc/mysql/Dockerfile
    networks:
      - backend
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  composer:
    container_name: composer
    build:
      context: .
      dockerfile: ./etc/composer/Dockerfile
    networks:
      - backend
    platform: linux/amd64
    volumes:
      - ./app:/app
    depends_on:
      - php-fpm

networks:
  backend:
  frontend:

volumes:
  mysql:
  testf: