version: "3.9"

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./etc/php-fpm/Dockerfile
    container_name: hello_php-fpm
    environment:
      MYSQL_DATABASE: "hello"
      MYSQL_PASSWORD: "OLr/rb3+A3HQMpnyI1c/WAlf+rc="
      MYSQL_SERVER: "mysql"
      MYSQL_USER: "hello"
    networks:
      - internal
    volumes:
      - ./app:/app

  http-proxy:
    build:
      context: .
      dockerfile: ./etc/http-proxy/Dockerfile
    container_name: hello_http-proxy
    networks:
      - external
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/http-proxy/development/default.conf:/etc/nginx/conf.d/default.conf

  api-server:
    build:
      context: .
      dockerfile: ./etc/api-server/Dockerfile
    container_name: hello_api-server
    depends_on:
      - php-fpm
    networks:
      - external
      - internal
    volumes:
      - ./app:/app
      - ./etc/api-server/development/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    build:
      context: .
      dockerfile: ./etc/mysql/Dockerfile
    container_name: mysql
    environment:
      MYSQL_DATABASE: "hello"
      MYSQL_PASSWORD: "OLr/rb3+A3HQMpnyI1c/WAlf+rc="
      MYSQL_ROOT_PASSWORD: "BCML9z2cL5e/gu6pzCbGrxuCa00="
      MYSQL_USER: "hello"
    networks:
      - internal
    platform: linux/amd64
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    build:
      context: .
      dockerfile: ./etc/adminer/Dockerfile
    container_name: hello_adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - internal
    ports:
      - 8080:8080

networks:
  internal:
  external:

volumes:
  mysql: