name: CI to Docker Hub

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest        
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ironex/nginx
        id: docker_build_ironex_nginx
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./etc/nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nginx:latest      

      - name: Build and push ironex/php-fpm
        id: docker_build_ironex_php-fpm
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./etc/php-fpm/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/php-fpm:latest   
          
      - name: Build and push ironex/composer
        id: docker_build_ironex_composer
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./etc/composer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/composer:latest             

      - name: Build and push ironex/mysql
        id: docker_build_ironex_mysql
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./etc/composer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/composer:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
